# Generated by Django 4.0.3 on 2022-04-08 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='organiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.organisersmodel'),
        ),
    ]
