# Generated by Django 4.0.3 on 2022-04-08 05:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_teammodel'),
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamWinnerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.eventmodel')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_first_place', to='authentication.teammodel')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_second_place', to='authentication.teammodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoloWinnerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.eventmodel')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_first_place', to='authentication.participantsmodel')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_second_place', to='authentication.participantsmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
