# Generated by Django 4.0.3 on 2022-04-21 13:49

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teameventmodel',
            name='team_size',
            field=models.PositiveSmallIntegerField(validators=[app.validators.validate_team_size]),
        ),
    ]
