# Generated by Django 4.0.3 on 2022-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_soloeventmodel_organiser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soloparticipation',
            name='has_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='has_attended',
            field=models.BooleanField(default=False),
        ),
    ]
