# Generated by Django 4.0.3 on 2022-04-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammodel',
            name='size',
        ),
    ]
