# Generated by Django 4.0.3 on 2022-04-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_teammodel_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantsmodel',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='participantsmodel',
            name='vaccination',
        ),
    ]
